spring:
  jpa:
    generate-ddl: true
  datasource:
      url: "jdbc:mysql://localhost/product"
      username: root
      password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cache:
      type: redis
  redis:
    host: 127.0.0.1
    port: 6379